export const TYPES = {
    ADD_TO_ORDER: "ADD_TO_ORDER",
    REMOVE_ONE_FROM_ORDER: "REMOVE_ONE_FROM_ORDER",
    REMOVE_ALL_FROM_ORDER: "REMOVE_ALL_FROM_ORDER",
    CLEAR_ORDER: "CLEAR_ORDER",
    ADITION_TOTAL_ORDER: "ADITION_TOTAL_ORDER",
}